-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 01:34:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbclinicadesaude
-- -----------------------------------------------------
-- Autor: Clenildon Ferreira

-- -----------------------------------------------------
-- Schema dbclinicadesaude
--
-- Autor: Clenildon Ferreira
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbclinicadesaude` DEFAULT CHARACTER SET utf8 ;
USE `dbclinicadesaude` ;

-- -----------------------------------------------------
-- Table `dbclinicadesaude`.`tbmedico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbclinicadesaude`.`tbmedico` (
  `id_crm` INT(11) UNSIGNED NOT NULL,
  `n_profisional` VARCHAR(60) NOT NULL,
  `m_telefone` VARCHAR(14) NOT NULL,
  `dia_disponive` DATE NOT NULL,
  `hora_disponivel` TIME NOT NULL,
  PRIMARY KEY (`id_crm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbclinicadesaude`.`tbespecialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbclinicadesaude`.`tbespecialidade` (
  `id_especialidade` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `e_nome` VARCHAR(60) NOT NULL,
  `tbmedico_id_crm` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_especialidade`),
  INDEX `fk_tbespecialidade_tbmedico1_idx` (`tbmedico_id_crm` ASC),
  CONSTRAINT `fk_tbespecialidade_tbmedico1`
    FOREIGN KEY (`tbmedico_id_crm`)
    REFERENCES `dbclinicadesaude`.`tbmedico` (`id_crm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbclinicadesaude`.`tbpaciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbclinicadesaude`.`tbpaciente` (
  `id_paciente` INT(11) UNSIGNED NOT NULL,
  `p_nome` VARCHAR(60) NOT NULL,
  `data_de_nascimento` DATE NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `endereco` VARCHAR(30) NOT NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `p_telefone` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id_paciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbclinicadesaude`.`tbformacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbclinicadesaude`.`tbformacao` (
  `tbmedico_id_crm` INT(11) UNSIGNED NOT NULL,
  `tbespecialidade_id_especialidade` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`tbmedico_id_crm`, `tbespecialidade_id_especialidade`),
  INDEX `fk_tbmedico_has_tbespecialidade_tbespecialidade1_idx` (`tbespecialidade_id_especialidade` ASC),
  INDEX `fk_tbmedico_has_tbespecialidade_tbmedico_idx` (`tbmedico_id_crm` ASC),
  CONSTRAINT `fk_tbmedico_has_tbespecialidade_tbmedico`
    FOREIGN KEY (`tbmedico_id_crm`)
    REFERENCES `dbclinicadesaude`.`tbmedico` (`id_crm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbmedico_has_tbespecialidade_tbespecialidade1`
    FOREIGN KEY (`tbespecialidade_id_especialidade`)
    REFERENCES `dbclinicadesaude`.`tbespecialidade` (`id_especialidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbclinicadesaude`.`tbprocedimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbclinicadesaude`.`tbprocedimento` (
  `id_procedimento` INT(11) UNSIGNED NOT NULL,
  `pro_nome` VARCHAR(60) NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`id_procedimento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbclinicadesaude`.`tbatendimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbclinicadesaude`.`tbatendimentos` (
  `id_atendimentos` INT(11) UNSIGNED NOT NULL,
  `horario_atendimento` TIME NOT NULL,
  `dia_atendimento` DATE NOT NULL,
  `valor_total` FLOAT NOT NULL,
  `presenca` VARCHAR(1) NULL,
  `tbmedico_id_crm` INT(11) UNSIGNED NOT NULL,
  `tbpaciente_id_paciente` INT(11) UNSIGNED NOT NULL,
  `tbprocedimento_id_procedimento` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_atendimentos`),
  INDEX `fk_tbatendimentos_tbmedico1_idx` (`tbmedico_id_crm` ASC),
  INDEX `fk_tbatendimentos_tbpaciente1_idx` (`tbpaciente_id_paciente` ASC),
  INDEX `fk_tbatendimentos_tbprocedimento1_idx` (`tbprocedimento_id_procedimento` ASC),
  CONSTRAINT `fk_tbatendimentos_tbmedico1`
    FOREIGN KEY (`tbmedico_id_crm`)
    REFERENCES `dbclinicadesaude`.`tbmedico` (`id_crm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbatendimentos_tbpaciente1`
    FOREIGN KEY (`tbpaciente_id_paciente`)
    REFERENCES `dbclinicadesaude`.`tbpaciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbatendimentos_tbprocedimento1`
    FOREIGN KEY (`tbprocedimento_id_procedimento`)
    REFERENCES `dbclinicadesaude`.`tbprocedimento` (`id_procedimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbclinicadesaude`.`tbusuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbclinicadesaude`.`tbusuario` (
  `id_user` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `u_nome` VARCHAR(30) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
